name: Python Tests CI

# performs: linting, auto-styling, and unit testing
# executed on merge with main branch before proceeding
# to docker build and push workflow in docker-image.yml

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The Black formats to 88 chars wide and needs E203 ignored
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --extend-ignore E203 --statistics
      - name: Autoformat with black
        run: |
          black questionnaire/
          black tests/.py
      - name: Test with pytest
        run: |
          pytest