name: ARM64 test

on:
  push:
    branches: [ feature-formbuilder ]
  pull_request:
    branches: [ feature-formbuilder ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Pipenv
      run: |
        if [[ `uname` != "Darwin" ]]; then sudo apt install pipenv; fi
        export PIPENV_VENV_IN_PROJECT=1
    - name: Install Dependencies
      run: |
        if [ -f Pipfile ]; then pipenv install; fi
    - name: Lint Python with flake8
      run: |
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        pipenv run flake8 . --count --exit-zero --config .flake8 --statistics
    - name: Lint HTML and Jinja with djLint
      run: |
        pipenv run djlint questionnaire/templates/ --profile=jinja --configuration .djlintrc --warn --statistics
    - name: Autoformat with black
      run: |
        pipenv run black .